"""Type stubs for markstone."""

from typing import Union
from types import ModuleType

__version__: str
AST_SCHEMA_VERSION: int

class MarkstoneError(Exception): ...
class InputTooLargeError(MarkstoneError): ...
class DepthExceededError(MarkstoneError): ...
class InvalidUtf8Error(MarkstoneError): ...

def to_html(input: Union[str, bytes]) -> str: ...
def to_ast(input: Union[str, bytes]) -> str: ...

class _ActosModule(ModuleType):
    __version__: str
    AST_SCHEMA_VERSION: int
    def to_html(self, input: Union[str, bytes]) -> str: ...
    def to_ast(self, input: Union[str, bytes]) -> str: ...

actos: _ActosModule
